### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by markcellis** [vranki/ExtPlane-Panel#17]
This might be more of a question than an issue. I'm making some enhancements to the PFD and I have also added a panel item, an enumerated indicator that can support bit masks for datarefs that have multiple meanings depending on how the bits are set. All is working well but I feel that I should create some user documentation for the enumerated indicator.

I don't see where there is a documentation file that can be distributed with pre-built binaries. If there is one can you tell me where it is so I can enhance it. If there isn't one do you guys mind if I create one that we can all add to?

Mark

**Comment by vranki** [comment]
I think we could make use of GitHub wiki feature documented here: https://help.github.com/articles/about-github-wikis/

Maybe we should move the documentation in the readme to wiki pages so it could be organized more efficiently and keep readme as simple welcome page.

**Comment by vranki** [comment]
Looks like Dan has already created wiki pages. You could add a new page here with your documentation. Let me know if you need some authorization. 

https://github.com/vranki/ExtPlane-Panel/wiki

**Comment by markcellis** [comment]
Ville,

 

I’m making a fair number of enhancements, mostly to ExtPlane Panel but also to the ExtPlane QT client for the simulator, adding simulated datarefs. I have one pull request in now but more is to come. I’m not sure at what point you want me to be added as a collaborator to do the merges. I definitely would like access to editing the Wiki Pages

 

Mark

**Comment by vranki** [comment]
You should have access to wiki - at least you're marked as contributor for the repository.
Closing this issue, repopen it if you still can't edit the wiki.
