### ISSUE TITLE
Display data ref value with custom label

### ISSUE THREAD

**Issue by bitonator** [vranki/ExtPlane-Panel#18]
Fantastic project, just saved me tons of headaches while flying.

Just found a simple requirement missing. I want to be able ti display data ref values with labels.

My current best option is to use debug data refs but it prints the whole data ref name. Can you add a label setting to this? Would be damn useful.

**Comment by dankrusi** [comment]
Hey,

My widget, display/indicator, can do this. Just set the labels to empty, and enable "Show Value".

-dan

**Comment by bitonator** [comment]
I don't see this widget anywhere in "Add Item". Upgraded to the latest version. Not avaiable on Mac maybe?

**Comment by dankrusi** [comment]
Are you building from source or using a binary?
