### ISSUE TITLE
Port number is NOT required for connection

### ISSUE THREAD

**Issue by mocsa** [vranki/ExtPlane-Panel#21]
The default IP address in ExtPlane-Panel settings is 127.0.0.1:51000. I changed this to my local IP address 192.168.xxx.xxx:51000, but ExtPlane-Panel did not connect. Neither the Windows nor the Android version.
In the meantime, I verified using Telnet that my ExtPlane plugin was working correctly. I was able to change dataref values in X-Plane via telnet text commands.
After tearing much of my hair out, I accidentally omitted the port number in ExtPlane-Panel and voila, it connected immediately. The same happened in Android.
Therefore I suggest to remove the port number from the default settings. (Unless it is some kind of strange problem in my home network, which I think it isn't.)

**Comment by vranki** [comment]
Thanks, this should be fixed.
