### ISSUE TITLE
App creates invalid saved files

### ISSUE THREAD

**Issue by mocsa** [vranki/ExtPlane-Panel#22]
When I start up my self-built version of ExtPlane-Panel, there are no panels in the Manage Panels dialog. I did not know this, so I created a panel with several widgets. I saved it with "Save Profile As...". The INI file was successfully created, it contained all settings. But when I loaded it with "Load Profile", I got a completely black screen. I could only find out the root-cause via debugging. The INI file had no "[panel-0]" section, therefore ExtPlane-Panel simply did not load the file.

I suggest to display some error message when the file load fails.

After I manually added a new panel in the Manage Panels dialog the saving and loading of files worked flawlessly.

I experienced this in a self-built version of ExtPlane-Panel based on commit 6e1cc30d3b9.

**Comment by mocsa** [comment]
Looking closer at the file, when there was no panel in the dialog, the saved file contained [gauge-0] and [gauge-1] sections at the top level.

However, the correct file contains [panel-0] and [panel-1] sections at the top level, while gauges are within these sections in the format gauge-0\width=250 and gauge-1\width=250.

**Comment by vranki** [comment]
Notice that I'm continuing development of ExtPlane-Panel in branch qml-ui which is practically a complete rewrite of the application. Currently it has only few instruments and is not ready for public consumption. 

I'm also quite busy with other stuff, so there hasn't been development for a while. I'll continue when I have time (there's one simulator waiting I need to set up with the new version..).

https://github.com/vranki/ExtPlane-Panel/tree/feature/qml-ui

**Comment by vranki** [comment]
ExtPlane-Panel 2 uses completely rewritten storage for panels. Closing.
