### ISSUE TITLE
Raspberry Pi install - error with step 3a

### ISSUE THREAD

**Issue by eliassmith02** [vranki/ExtPlane-Panel#31]
Had the following error come up when started step 3a

pi@raspberrypi:~/ExtPlane-Panel $ dpkg-buildpackage -rfakeroot -b
dpkg-buildpackage: info: source package extplane-panel
dpkg-buildpackage: info: source version 2.0.3
dpkg-buildpackage: info: source distribution UNRELEASED
dpkg-buildpackage: info: source changed by Ville Ranki <ville.ranki@iki.fi>
dpkg-buildpackage: info: host architecture armhf
 dpkg-source --before-build ExtPlane-Panel
dpkg-checkbuilddeps: error: Unmet build dependencies: qtdeclarative5-dev libqt5svg5-dev
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)

**Comment by vranki** [comment]
Updated readme with correct dependency packages. Please try again and reopen if it still fails. I haven't done a Raspbian build myself for long time so this is untested. Thanks for reporting.
