### ISSUE TITLE
Add support for QML panel items

### ISSUE THREAD

**Issue by vranki** [vranki/ExtPlane-Panel#6]
QML is really, really nice way of doing GUI stuff. It would also be very good (and quick) way to create new instruments for Extplane-panel. 

Adding support for QML would require at least 
- PanelItem that contains QML widget and plumbing and UI to support several QML instruments
- Custom QML elements to provide access to DataRefs and other supported functions and to item settings

I'll probably start work on this during Q3/2013.

**Comment by RangerGH** [comment]
I'm interested in working on the QML version.  I have ExtPlane building under QT 5.13 and have checked out the feature/qmlui branch.  What do I need to do to get things started?  I have uncommented the qmlui subidr and will try and build.  Any hints and tips on working on it after that.

ExtPlane is a fantastic application.  I have been looking for something to put X-Plane's information on separate monitors and build my own information panels.

Thank you.

**Comment by vranki** [comment]
Hi,

Sorry for slow reply, I've been away for a while.

The qml branch should build without changes (just tested).

git checkout feature/qml-ui
qmake
make

This should provide a runnable binary qmlui/qmlui

What environment are you building in? Are you getting some
errors? Are you sure you have up to date code checked out
from correct branch?

**Comment by RangerGH** [comment]
I understand.  No problem.

I'm currently using Qt 5.13 on Windows as that's where my XPlane is for now.  I got ExtPlane to build and also got the qml-ui to build.  I'm currently going through it working on figuring out the code and getting a feel for how it works.  Then I'll try adding some simple stuff.

**Comment by vranki** [comment]
Merged in master now.
